name: dash_board_ieee
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  hive: ^2.2.3
  gap: ^3.0.1
  flutter_easyloading: ^3.0.5
  dio: ^5.7.0
  google_fonts: ^6.2.1
  either_dart: ^1.0.0
  flutter_secure_storage: ^9.2.2
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  pretty_dio_logger: ^1.4.0
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.15
  go_router: ^14.6.1
  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  logger: ^2.5.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.4
  device_preview: ^1.2.0
  introduction_screen: ^3.1.14
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  color: "#207DA9"
  image: "assets/images/logo.png"
